#ifndef lv_resources_hpp
#define lv_resources_hpp

#include "img/img_alarm.hpp"
#include "img/img_arrow_back.hpp"
#include "img/img_arrow_down.hpp"
#include "img/img_arrow_up.hpp"
#include "img/img_charge.hpp"
#include "img/img_chart.hpp"
#include "img/img_error.hpp"
#include "img/img_fan.hpp"
#include "img/img_flag.hpp"
#include "img/img_info.hpp"
#include "img/img_logo.hpp"
#include "img/img_pause.hpp"
#include "img/img_play.hpp"
#include "img/img_process.hpp"
#include "img/img_sand_watch.hpp"
#include "img/img_sort_left.hpp"
#include "img/img_sort_rigth.hpp"
#include "img/img_tempC.hpp"
#include "img/img_update.hpp"
#include "img/img_warning.hpp"
#include "img/img_water_glass.hpp"
#include "img/img_water_hose.hpp"
#include "img/img_checkmark.hpp"

#include "fonts/OpenSans_bold_12px.hpp"
#include "fonts/OpenSans_bold_14px.hpp"
#include "fonts/OpenSans_bold_16px.hpp"
#include "fonts/OpenSans_bold_20px.hpp"
#include "fonts/OpenSans_bold_24px.hpp"
#include "fonts/OpenSans_regular_12px.hpp"
#include "fonts/OpenSans_regular_14px.hpp"
#include "fonts/OpenSans_regular_16px.hpp"
#include "fonts/OpenSans_regular_20px.hpp"
#include "fonts/OpenSans_regular_24px.hpp"

#endif